### ISSUE TITLE
multiple data source in jBilling

### ISSUE THREAD

**Issue by Amitkumar0** [WebDataConsulting/billing#1]
Hi as is see , we can define multiple data source on a grails projet depending on the envirement configuration

i wan to know , if there is a solution to define tow data source for the production enviroment and switch to the second datasource if the firs is not repondin

jbilling can detect that the connexion pool is down , can i associate an action if this excpetion is thrown ( switchin to the second data source )

**Comment by vikasbo** [comment]
Question: Why would we want the production instance to fall back on a staging or a dev environment in case the production db is not availalbe?

**Comment by vikasbo** [comment]
Grails allows configuring environment specific dataSources in the DataSource file.
