### ISSUE TITLE
Issue compiling "invalid source release: 1.8"

### ISSUE THREAD

**Issue by isparkes** [WebDataConsulting/billing#10]
While compiling on my machine, I get:

```
| Error Compilation error: startup failed:
Invalid commandline usage for javac.
javac: invalid source release: 1.8
```

My machine has a default JDK7 on the path, and an optional JDK8 installed, which I am using for this project.

After tracing the error back into Groovy, I found that the problem was that my JAVA_HOME pointed to JDK7, and my PATH pointed to JDK8.

I made a "source.me" file to remind me to keep these two in sync in future. Perhaps we can add such a file to the installation?

**Comment by vikasbo** [comment]
Thanks for the sharing @isparkes. I have added it here https://github.com/WebDataConsulting/billing/blob/master/README.md

**Comment by isparkes** [comment]
Great, thanks!
