### ISSUE TITLE
unable to compile, error on "grails clean" as per guide

### ISSUE THREAD

**Issue by dynamicpacket** [WebDataConsulting/billing#15]
How to recreate:
1) launch new vm with ubuntu 16.04.1
2) Install oracle jdk 1.8 and update PATH
3) Unzip grails 2.4.3 (https://github.com/grails/grails-core/releases/download/v2.4.3/grails-2.4.3.zip) to /opt/grails-2.4.3 & update PATH
4) cd /opt && git clone https://github.com/WebDataConsulting/billing.git
5) cd /opt/billing && grails clean

Result:
| Configuring classpath
| Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5 (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5 (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5 (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5 (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5 (Use --stacktrace to see the full trace)
| Error Failed to read artifact descriptor for org.slf4j:jcl-over-slf4j:jar:1.7.5
| Run 'grails dependency-report' for further information.

**Comment by dynamicpacket** [comment]
turned out to be a problem with maven repo (repo1.maven.org/maven2 sending back 403 forbidden) :0(

**Comment by vikasbo** [comment]
No problem. Thanks for the update. (y).
