### ISSUE TITLE
From Internet - Signed up jBilling, cannot find the reset password email.

### ISSUE THREAD

**Issue by vikasbo** [WebDataConsulting/billing#7]

**Comment by manishagupta592** [comment]
1. Download the jBilling CE 4.1.1. Edition [here](http://webdataconsulting.github.io/)
2. Extract the zip: unzip -q jbilling-community-4.1.1.zip
3. cd jbilling-community-4.1.1/bin/
4. chmod +x *.sh
5. ./startup.sh && tail -f ../logs/catalina.out 
6. Start the app server: http://localhost:8080/jbilling/login
7. For signing a new company, type the URL: http://localhost:8080/jbilling/signup
8. Provide the mandatory fields. Save Changes
9. Now to reset the password, go to directory jbilling-community-4.1.1/jbilling/resources/, open the file emails_sent.txt and copy the reset password link and paste in the URL: http://localhost:8080/jbilling/RESET-PASSWORD-LINK 
10. Set the password and Submit.
