### ISSUE TITLE
Provisioning 

### ISSUE THREAD

**Issue by ahmeddrira** [WebDataConsulting/billing#9]
what about jbilling and provisionning module

**Comment by vikasbo** [comment]
@ahmeddrira - Thank you for your request. We can provide the provisioning as it exists on jBilling CE 3.x and bring it on to 4.x. It will be functional. However, if your requirements are simple, I would recommend you to share those, and we can provide a much lighter implementation. 

Let me know what you need and we can work on it.

Thanks
Vikas Bodani

**Comment by ahmeddrira** [comment]
Hi vikasbo , 
i am working on that, i ve just want to know if you have dealt with the provisioning module, if it it work on the CE edition and if it was tested  
in my case i will implement a specific plugin  for my ressources .
may be i will return to the community  with my feedback

**Comment by vikasbo** [comment]
@ahmeddrira Sounds great. Indeed provisioning works really well on the community edition and has been tested very well. You can find it implemented on the v3.x [here](https://github.com/WebDataConsulting/billing/tree/jBilling-3.1.x)

Looking forward to your contribution (Y).

Vikas

**Comment by vikasbo** [comment]
We have replaced the original Provisioning module with a completely UI configurable provisioning module. Its basic invokation mechanism has been developed. All we need to do is tie the invokations to specific integrations.
